name: Automatic Deployment

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Validate configuration
      run: |
        echo "Validating server.js"
        node -e "require('./config/server.js');"
        echo "Validating admin.js"
        node -e "require('./config/admin.js');"

    - name: Build project
      run: npm run build

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY $USER@$HOST "cd /path/to/your/project && git pull && npm install && npm run build && pm2 restart all"

