name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker build -t vishweshrushi/strapi:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.vishweshrushi }}" | docker login -u vishweshrushi --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push vishweshrushi/strapi:latest
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy Infrastructure
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_VALUE }}
