name: Pipeline for EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          port: 22
          degub: true
          script: | 
            sudo apt update -y
            sudo apt install nodejs npm -y
            sudo npm install -g pm2
            git clone https://github.com/RushiVishwesh/strapi-app.git
            cd strapi-app
            npm install
            npm run build
            pm2 start "npm run start" --name=strapi-app
            echo "application started successfully to ec2"
